id: P001708
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:53.418478
source_metadata:
  id: bdr:W27923
  title: འཇམ་དཔལ་གཤིན་རྗེ་དྲེགས་པ་འཇོམས་བྱེད་ཀྱི་ཆོས་སྐོར།
  author: ''
  volumes:
    14ec451643704d43b2892d15fdb667e7:
      image_group_id: I4525
      title: ''
      volume_number: 1
      total_pages: 466
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
