id: P001708
initial_creation_type: ocr
source_metadata:
  id: bdr:W27923
  title: འཇམ་དཔལ་གཤིན་རྗེ་དྲེགས་པ་འཇོམས་བྱེད་ཀྱི་ཆོས་སྐོར།
  author: ''
  volumes:
    14ec451643704d43b2892d15fdb667e7:
      image_group_id: I4525
      title: ''
      volume_number: 1
      total_pages: 466
