id: I398A8868
legacy_id: P001708
ocr_import_info:
  bdrc_scan_id: W27923
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:05:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:09:53.792908+00:00'
last_modified: 2022-09-02 16:10:43.065787
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27923
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27923
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དཔལ་གཤིན་རྗེ་དྲེགས་པ་འཇོམས་བྱེད་ཀྱི་ཆོས་སྐོར།
  author: གཏེར་བདག་གླིང་པ་འགྱུར་མེད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.8097751476951325
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I4525:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4525
      total_pages: 466
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4525.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8097751476951325
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
